// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tWhT153005I4Se37Z19k2qUgl3-xg34',
    appId: '1:327456366591:android:a775a53c4774e5610091ca',
    messagingSenderId: '327456366591',
    projectId: 'univ-fest-mobile-order',
    databaseURL: 'https://univ-fest-mobile-order-default-rtdb.firebaseio.com',
    storageBucket: 'univ-fest-mobile-order.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbEUElBKmi6FBQqn7jP71SQCm3-kqIcaY',
    appId: '1:327456366591:ios:cdb87d07c8cc07c40091ca',
    messagingSenderId: '327456366591',
    projectId: 'univ-fest-mobile-order',
    databaseURL: 'https://univ-fest-mobile-order-default-rtdb.firebaseio.com',
    storageBucket: 'univ-fest-mobile-order.appspot.com',
    androidClientId: '327456366591-2651arvrusp99n87d049ehmo185ltiq1.apps.googleusercontent.com',
    iosClientId: '327456366591-kmsdhvmq444okts3205lc8tbl7aqdno1.apps.googleusercontent.com',
    iosBundleId: 'com.example.univFestHost',
  );

}